baseURL = "https://supery.top/"
languageCode = "zh-cn"
title = "æ‚²ä¼¤åœŸè±†"
theme = "PaperMod"

[params]
  defaultTheme = "dark"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  
  [params.homeInfoParams]
    Title = "æ‚²ä¼¤åœŸè±† ğŸ¥”"
    Content = "ä¸€ä¸ªæœ‰è¶£çš„äºº Â· çƒ­çˆ±å¼€å‘ Â· æ¢ç´¢æ— é™å¯èƒ½"

[menu]
  [[menu.main]]
    name = "é¦–é¡µ"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "æ–‡ç« "
    url = "/posts/"
    weight = 2